### ISSUE TITLE
Failure to migrate

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#272]
![](https://dl.dropbox.com/s/ba8gv0vdxqph4or/Screenshot%202015-11-22%2014.38.32.png?dl=0)

![](https://dl.dropbox.com/s/6z0kev4n3rnxg8i/Screenshot%202015-11-22%2014.41.09.png?dl=0)

any ideas @RobertAKARobin ? https://github.com/ga-dc/garnet/commit/6cd2ccdc2efa1d18394eb1169d90932d2e296167

**Comment by jshawl** [comment]
The full trace from `rake db:migrate`

```
== 20151104040728 RemoveExcessMemberships: migrating ==========================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `ancestry_was' for #<Group:0x007fbc3931a978>/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:91:in `child_ancestry'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:187:in `child_conditions'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:191:in `children'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:49:in `block in at_path'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `each'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `each_with_index'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `at_path'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:4:in `block in change'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:3:in `each'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:3:in `change'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/jesse/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/jesse/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `ancestry_was' for #<Group:0x007fbc3931a978>
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:91:in `child_ancestry'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:187:in `child_conditions'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/ancestry-2.1.0/lib/ancestry/instance_methods.rb:191:in `children'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:49:in `block in at_path'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `each'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `each_with_index'
/Users/jesse/ga/ga-dc/garnet/app/models/group.rb:47:in `at_path'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:4:in `block in change'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:3:in `each'
/Users/jesse/ga/ga-dc/garnet/db/migrate/20151104040728_remove_excess_memberships.rb:3:in `change'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/jesse/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/jesse/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/jesse/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```
